### ISSUE TITLE
The CreationTime property cannot be customized to modify the value

### ISSUE THREAD

**Issue by dotnet9** [masastack/MASA.Framework#564]
### Description

The CreationTime is initialized in AuditAggregateRoot. I wrote the method of modifying the time in the inherited class. The last time to write to the database is not the seed time, but the time when the framework is initialized.

![132f50b25ef90c89558286363b50fe1](https://user-images.githubusercontent.com/19390373/232519605-2d1b070b-9d83-4644-91b6-006c0be71665.png)

This is the value that comes up when debugging：

![edd17dc49aee74d3b134be92e27daef](https://user-images.githubusercontent.com/19390373/232519777-b768e9cd-3d9e-4681-b7d4-2c74d98ea65e.png)

The value inserted by the database is not the expected seed data time, but the current system time when the data was created:

![bc21c7533ac47dad39c353a619505a7](https://user-images.githubusercontent.com/19390373/232520179-9a0d3de0-ecec-4de2-a590-dc68f519793f.png)

### Expected behavior

Can customize and modify CreationTime

### Actual behavior

CreationTime cannot be customized

### .NET version

.NET 8 Preview 3

### MASA Framework version

1.0.0-preview.28

**Comment by zhenlei520** [comment]
When the attribute is assigned, it will not be assigned again, this will be fixed in subsequent versions

**Comment by zhenlei520** [comment]
Fixed in [#566](https://github.com/masastack/MASA.Framework/pull/566)

**Comment by dotnet9** [comment]
I have updated p30, but this issue still exists

> Fixed in [#566](https://github.com/masastack/MASA.Framework/pull/566)

I have updated p30, but this issue still exists

**Comment by zhenlei520** [comment]
> I have updated p30, but this issue still exists
> 
> > Fixed in [#566](https://github.com/masastack/MASA.Framework/pull/566)
> 
> I have updated p30, but this issue still exists

It will be resolved in the next version, not [preview.30](https://github.com/masastack/MASA.Framework/releases/tag/1.0.0-preview.30)

**Comment by zhenlei520** [comment]
Fixed in [1.0.0-preview.31](https://github.com/masastack/MASA.Framework/releases/tag/1.0.0-preview.31) @dotnet9

**Comment by dotnet9** [comment]
> Fixed in [1.0.0-preview.31](https://github.com/masastack/MASA.Framework/releases/tag/1.0.0-preview.31) @dotnet9

Thanks very much. After upgrade the nuget package, these fields have been updated normally.

**Comment by dotnet9** [comment]
Thank you!
